name: Output information
on: workflow_dispatch # we only want this Workflow to be trigger manually
jobs:
  info: # we are defining just 1 job named "info"
    runs-on: ubuntu-latest # this job runs in ubuntu
    steps:
      - name: Output GitHub context
        run: echo "${{ toJSON(github) }}"
